-- Initial schema migration for a new GameGear Hub database.
-- Apply this migration once to the selected database before running the demo seed.

CREATE TABLE Customer (
  customerID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customerName VARCHAR(100) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  phone VARCHAR(30) NOT NULL,
  password VARCHAR(255) NOT NULL,
  address TEXT NULL,
  role ENUM('customer','admin') NOT NULL DEFAULT 'customer',
  status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Category (
  categoryID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  categoryName VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE Product (
  productID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  categoryID INT UNSIGNED NOT NULL,
  productName VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  specifications TEXT NOT NULL,
  price DECIMAL(12,2) UNSIGNED NOT NULL,
  stockQuantity INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  imageURL VARCHAR(1000) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_category FOREIGN KEY(categoryID) REFERENCES Category(categoryID)
) ENGINE=InnoDB;

CREATE TABLE Review (
  reviewID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customerID INT UNSIGNED NOT NULL,
  productID INT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NULL,
  comment TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_customer FOREIGN KEY(customerID) REFERENCES Customer(customerID) ON DELETE CASCADE,
  CONSTRAINT fk_review_product FOREIGN KEY(productID) REFERENCES Product(productID) ON DELETE CASCADE,
  CONSTRAINT uq_review_customer_product UNIQUE(customerID, productID),
  CONSTRAINT chk_review_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)
) ENGINE=InnoDB;

CREATE TABLE Cart (
  cartID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customerID INT UNSIGNED NOT NULL,
  totalItem INT UNSIGNED NOT NULL DEFAULT 0,
  totalAmount DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('Active','Converted','Abandoned') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cart_customer FOREIGN KEY(customerID) REFERENCES Customer(customerID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Cart_item (
  cart_item_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cartID INT UNSIGNED NOT NULL,
  productID INT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_cart_product UNIQUE(cartID, productID),
  CONSTRAINT fk_cart_item_cart FOREIGN KEY(cartID) REFERENCES Cart(cartID) ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_product FOREIGN KEY(productID) REFERENCES Product(productID)
) ENGINE=InnoDB;

CREATE TABLE `Order` (
  orderID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customerID INT UNSIGNED NOT NULL,
  orderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  subtotal DECIMAL(12,2) UNSIGNED NOT NULL,
  discount DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0,
  orderStatus ENUM('Pending','Processing','Delivered','Cancelled') NOT NULL DEFAULT 'Pending',
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_customer FOREIGN KEY(customerID) REFERENCES Customer(customerID)
) ENGINE=InnoDB;

CREATE TABLE Order_product (
  order_product_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  orderID INT UNSIGNED NOT NULL,
  productID INT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  unitPrice DECIMAL(12,2) UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_product_order FOREIGN KEY(orderID) REFERENCES `Order`(orderID) ON DELETE CASCADE,
  CONSTRAINT fk_order_product_product FOREIGN KEY(productID) REFERENCES Product(productID)
) ENGINE=InnoDB;

CREATE TABLE Payment (
  paymentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  orderID INT UNSIGNED NOT NULL UNIQUE,
  paymentMethod VARCHAR(50) NOT NULL,
  amount DECIMAL(12,2) UNSIGNED NOT NULL,
  paymentStatus ENUM('Pending','Paid','Failed') NOT NULL DEFAULT 'Pending',
  transactionID VARCHAR(100) UNIQUE,
  paid_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payment_order FOREIGN KEY(orderID) REFERENCES `Order`(orderID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Shipment (
  shipmentID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  orderID INT UNSIGNED NOT NULL UNIQUE,
  receiverName VARCHAR(100) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  shippingAddress TEXT NOT NULL,
  shippingFee DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0,
  shipped_at DATETIME NULL,
  trackingNumber VARCHAR(100) NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_shipment_order FOREIGN KEY(orderID) REFERENCES `Order`(orderID) ON DELETE CASCADE
) ENGINE=InnoDB;
